name: chocolatine

on:
  push:
    branches-ignore: ['no-ga/**']
  pull_request:
    branches-ignore: ['no-ga/**']

permissions:
  contents: read

env:
  MIRROR_SSH_URL: ${{ vars.MIRROR_SSH_URL }}
  EXECUTABLES: ${{ vars.EXECUTABLES }}

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
      - name: check_coding_style
        run: banana-check-repo
      - name: compile
        run: make
        timeout-minutes: 2
        env:
          CC: epiclang
      - name: clean
        run: make clean

  run_tests:
    needs: check_compilation_and_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
      - name: run_tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_SSH_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
